#Users 

# u1 = User.create(first_name: "Maleeha", last_name: "Bhuiyan", username: "Mbhuiyan99", password_digest: "12345")

# #JournalEntries

e1 = Entry.create(
    user_id: 1,
    great_one: "I had Starbucks.",
    great_two: "For my little sister.",
    great_three: "For my bed.",
    today_one: "I will nap for a few hours.",
    today_two: "Eating a donut.",
    today_three: "Spend time with my mom.",
    daily_affirmation: "I am beautiful",
    date: "August 25, 2020"
)
e2 = Entry.create(
    user_id: 1,
    great_one: "I went to six flags.",
    great_two: "I found my favorite book online for free.",
    great_three: "I woke up with a smile.",
    today_one: "I will go for a run.",
    today_two: "I will email one of my friends.",
    today_three: "I will clean my room.",
    daily_affirmation: "I am capable.",
    date: "August 26, 2020"
)

#Moods

# m1 = Mood.create(user_id: 1, mood: "highlight")


#boards 

b1 = Board.create(
    user_id: 1, 
    main_title: "Places I want to Go",
    sub_title_one: "CAPPADOCIA, TURKEY",
    body_one: "Cappadocia is a living example of just how odd yet beautiful nature can be. It presents a fantasy-like landscape which looks like it’s been plucked out of a fairy tale, alien-like hills and boulders that seem as if they’ve been transported from another planet.",
    img_url_one: "https://d3hne3c382ip58.cloudfront.net/files/uploads/bookmundi/resized/cms/hot-air-balloon-flying-over-cappadocia-1534391901-1000X561.jpg",
    sub_title_two: "WHITEHAVEN BEACH, WHITSUNDAYS, AUSTRALIA",
    body_two: "It’s easy to see why the Whitehaven Beach ranks among the most photographed beaches in the world. The magnificent 7 km stretch of white sand that feels like your own private slice of heaven presents an aura of peace and serenity, letting you experience relaxation at its very best.",
    img_url_two: "https://d3hne3c382ip58.cloudfront.net/files/uploads/bookmundi/resized/cms/whitehaven-beach-1534394654-1000X561.jpg",
    sub_title_three: "THE FAIRY POOLS, ISLE OF SKYE, SCOTLAND", 
    body_three: "You might suddenly start believing in fairies the moment your eyes fall on the Fairy Pool, an ethereal oasis that bewitches visitors with its crystal clear water, picture-perfect scenery and magical atmosphere.",
    img_url_three: "https://d3hne3c382ip58.cloudfront.net/files/uploads/bookmundi/resized/cms/the-fairy-pools-1534396580-1000X561.jpg",
    sub_title_four: "GRAND CANYON NATIONAL PARK, USA", 
    body_four: "There’s a reason more than 5 million people choose to visit the Grand Canyon each year. It’s one of the most magical destinations on the planet. Irrespective of how much you read about the Grand Canyon, you’re sure to end up being spellbound, for nothing prepares you for the magical sight that this wonder has to offer. ",
    img_url_four: "https://d3hne3c382ip58.cloudfront.net/files/uploads/bookmundi/resized/cms/grand-canyon-south-rim-1534399223-1000X561.jpg",
    sub_title_five: "HUACACHINA, PERU",
    body_five: "Psy lovers and artists will fall in love with Huacachina, a stunning desert oasis that leaves you mesmerized with its raw beauty and fantastical legends. Think of yourself sitting on a huge sand dune enjoying breath-taking sunset views as the landscape reveals vivid colors of red and yellow all around you. ",
    img_url_five: "https://d3hne3c382ip58.cloudfront.net/files/uploads/bookmundi/resized/cms/huacachina-1534400714-735X412.jpg",
    sub_title_six: "SALAR DE UYUNI, BOLIVIA",
    body_six: "The largest salt mine in the world is also one of its most beautiful wonders. Salar de Uyuni looks like one of those fantasy-like paintings of the renaissance era, but it proudly stands as one of the most stunning spectacles of South America.", 
    img_url_six: "https://d3hne3c382ip58.cloudfront.net/files/uploads/bookmundi/resized/cms/salar-de-uyuni-1534401792-1000X561.jpg",
    sub_title_seven: "PLITVICE LAKES NATIONAL PARK, CROATIA",
    body_seven: "No list of the most beautiful places in the world would ever be complete without mentioning Plitvice Lakes National Park in Croatia. This mesmerizing park is the largest national park in the country and is most famous for its 16 crystalline lakes that join one another through a series of cascades and waterfalls.", 
    img_url_seven: "https://d3hne3c382ip58.cloudfront.net/files/uploads/bookmundi/resized/cms/plitvice-lakes-national-park-1534405883-735X412.jpg",
    sub_title_eight: "MILFORD SOUND, NEW ZEALAND",
    body_eight: "Sydney Opera House, Waitomo Caves, Great Barrier Reef, Sydney Harbor Bridge, you have all kinds of attractions to keep you company while on tour to Australia and New Zealand. However, the moment your visit Milford Sound, everything else pales in view. ", 
    img_url_eight: "https://d3hne3c382ip58.cloudfront.net/files/uploads/bookmundi/resized/cms/milford-sound-1534408813-1000X561.jpg",
)

b2 = Board.create(
    user_id: 1, 
    main_title: "Home Garden Inspo",
    sub_title_one: "African Violet",
    body_one: "Small in stature but big in wow-factor, the African violet is fairly easy to care for, as flowering houseplants go. Available in hundreds of variations, this fuzzy-leafed houseplant typically blooms year round with blue, purple, or white flowers. ",
    img_url_one: "https://s3-production.bobvila.com/slides/30396/vertical_slide_wide/african_violet-flowering-houseplants.jpg?1551987229",
    sub_title_two: "Kalanchoe",
    body_two: "The kalanchoe is sometimes referred to as window's thrill, which makes sense since practically all you need to do is place it in a sunny spot on the windowsill and watch it bloom.",
    img_url_two: "https://s3-production.bobvila.com/slides/30438/vertical_slide_wide/Kalanchoe-flowering-houseplants.jpg?1551987236",
    sub_title_three: "Amaryllis", 
    body_three: "The amaryllis blooms in winter when there are almost no signs of life in your outdoor garden beds. Easy to grow in a small pot, you can expect bright, large flowers in shades of red, orange, and pink. ",
    img_url_three: "https://s3-production.bobvila.com/slides/30439/vertical_slide_wide/Amaryllis-flowering-houseplants.jpg?1551987237",
    sub_title_four: "Jasmine", 
    body_four: "Jasmine is a great pick for those who prefer natural air fresheners. Not only does this houseplant produce soft, star-shaped flowers, but it has a strong and sweet fragrance. ",
    img_url_four: "https://s3-production.bobvila.com/slides/30447/vertical_slide_wide/Jasmine-flowering-houseplants.jpg?1551987239",
    sub_title_five: "Christmas Cactus",
    body_five: "The trailing Christmas cactus has shiny green leaves that sprout small flowers in pinks or reds. ",
    img_url_five: "https://s3-production.bobvila.com/slides/30440/vertical_slide_wide/Christmas_Cactus-flowering-houseplants.jpg?1551987243",
    sub_title_six: "Gloxinia",
    body_six: "With its fluffy flowers and velvety leaves, Gloxina offers a lot of texture. Available in many bold shades, some varieties of this flowering houseplant have marbled or multi-colored blooms.", 
    img_url_six: "https://s3-production.bobvila.com/slides/30451/vertical_slide_wide/Gloxinia-flowering-houseplants.jpg?1551987245",
    sub_title_seven: "Geranium",
    body_seven: "Geraniums are a classic houseplant—and for good reason! The fragrant flowers come in an abundance of colors and bloom almost year round. Geraniums need only occasional watering and sunlight to add abundant beauty to your home.", 
    img_url_seven: "https://s3-production.bobvila.com/slides/30454/vertical_slide_wide/Geranium-flowering-houseplants.jpg?1551987248",
    sub_title_eight: "Chenille",
    body_eight: "You don't have to guess why this fuzzy plant is named for the French word for caterpillar. The unique flowers on this evergreen plant makes it a unique choice for hanging over the kitchen sink or in the window of the sitting room.", 
    img_url_eight: "https://s3-production.bobvila.com/slides/30443/vertical_slide_wide/Chennille-flowering-houseplants.jpg?1551987240",
)

# b3 = Board.create(
#     user_id: 1, 
#     main_title: "Books I want to Read",
#     sub_title_one: "",
#     body_one: "",
#     img_url_one: "",
#     sub_title_two: "",
#     body_two: "",
#     img_url_two: "",
#     sub_title_three: "", 
#     body_three: "",
#     img_url_three: "",
#     sub_title_four: "", 
#     body_four: "",
#     img_url_four: "",
#     sub_title_five: "",
#     body_five: "",
#     img_url_five: "",
#     sub_title_six: "",
#     body_six: "", 
#     img_url_six: "",
#     sub_title_seven: "",
#     body_seven: "", 
#     img_url_seven: "",
#     sub_title_eight: "",
#     body_eight: "", 
#     img_url_eight: "",
# )

# b4 = Board.create(
#     user_id: 1, 
#     main_title: "Drawing Inspo",
#     sub_title_one: "",
#     body_one: "",
#     img_url_one: "",
#     sub_title_two: "",
#     body_two: "",
#     img_url_two: "",
#     sub_title_three: "", 
#     body_three: "",
#     img_url_three: "",
#     sub_title_four: "", 
#     body_four: "",
#     img_url_four: "",
#     sub_title_five: "",
#     body_five: "",
#     img_url_five: "",
#     sub_title_six: "",
#     body_six: "", 
#     img_url_six: "",
#     sub_title_seven: "",
#     body_seven: "", 
#     img_url_seven: "",
#     sub_title_eight: "",
#     body_eight: "", 
#     img_url_eight: "",
# )

# b1 = Board.create(
    # user_id: 1, 
    # main_title: "",
    # sub_title_one: "",
    # body_one: "",
    # img_url_one: "",
    # sub_title_two: "",
    # body_two: "",
    # img_url_two: "",
    # sub_title_three: "", 
    # body_three: "",
    # img_url_three: "",
    # sub_title_four: "", 
    # body_four: "",
    # img_url_four: "",
    # sub_title_five: "",
    # body_five: "",
    # img_url_five: "",
    # sub_title_six: "",
    # body_six: "", 
    # img_url_six: "",
    # sub_title_seven: "",
    # body_seven: "", 
    # img_url_seven: "",
    # sub_title_eight: "",
    # body_eight: "", 
    # img_url_eight: "",
# )